# Generated by Django 5.2.17 on 2026-08-15 07:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('business_name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('customer_type', models.CharField(choices=[('Distributor', 'Distributor'), ('Retailer', 'Retailer'), ('Pharmacy', 'Pharmacy'), ('Grocery Store', 'Grocery Store'), ('Direct Customer', 'Direct Customer')], default='Distributor', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('distribution_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity_distributed', models.PositiveIntegerField(default=0)),
                ('delivery_method', models.CharField(choices=[('Company Delivery', 'Company Delivery'), ('Courier', 'Courier'), ('Customer Pickup', 'Customer Pickup')], default='Company Delivery', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=50)),
                ('delivery_status', models.CharField(choices=[('Preparing', 'Preparing'), ('For Delivery', 'For Delivery'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Preparing', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-distribution_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackagingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=100)),
                ('unit', models.CharField(default='pieces', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(help_text='For example: 100g tube', max_length=50, verbose_name='Product size')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.PositiveIntegerField(default=100, help_text='Warn when available stock falls to this level.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(default=django.utils.timezone.localdate)),
                ('receiver_name', models.CharField(max_length=100)),
                ('delivered_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('distribution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='core.distribution')),
            ],
            options={
                'ordering': ['-delivery_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready for Distribution', 'Ready for Distribution'), ('Distributed', 'Distributed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.product')),
            ],
            options={
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='distribution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.order'),
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('production_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiration_date', models.DateField()),
                ('quantity_produced', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_available', models.PositiveIntegerField(default=0, help_text='Units from this batch that have not been packaged yet.')),
                ('status', models.CharField(choices=[('Produced', 'Produced'), ('Ready for Packaging', 'Ready for Packaging'), ('Packaged', 'Packaged'), ('Completed', 'Completed')], default='Produced', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Production batches',
                'ordering': ['-production_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PackagingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('packaging_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_packaged', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('remaining_quantity', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packaging_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_records', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_records', to='core.productionbatch')),
            ],
            options={
                'ordering': ['-packaging_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.distribution')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='core.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_available', models.PositiveIntegerField(default=0)),
                ('date_packaged', models.DateField(default=django.utils.timezone.localdate)),
                ('expiration_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='core.product')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_rows', to='core.productionbatch')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'ordering': ['expiration_date', 'id'],
                'unique_together': {('product', 'batch')},
            },
        ),
    ]
